name: DawVert Libs

on: [push]

jobs:
  compile_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Linux
        uses: actions/checkout@v4
      - name: Compile
        run: |
          mkdir linux_64
          gcc src/bs_codec.c -shared -o linux_64/bs_codec.so
          gcc src/oki_codec.c -shared -o linux_64/oki_codec.so
          gcc src/yma_codec.c -shared -o linux_64/yma_codec.so
          gcc src/ymb_codec.c -shared -o linux_64/ymb_codec.so
          gcc src/ymz_codec.c -shared -o linux_64/ymz_codec.so
          g++ src/brr_codec.cpp -shared -o linux_64/brr_codec.so -static


  compile_windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Compile Windows
        uses: actions/checkout@v4
      - name: Compile
        run: |
          mkdir win_64
          gcc src/bs_codec.c -shared -o win_64/bs_codec.dll
          gcc src/oki_codec.c -shared -o win_64/oki_codec.dll
          gcc src/yma_codec.c -shared -o win_64/yma_codec.dll
          gcc src/ymb_codec.c -shared -o win_64/ymb_codec.dll
          gcc src/ymz_codec.c -shared -o win_64/ymz_codec.dll
          g++ src/brr_codec.cpp -shared -o win_64/brr_codec.dll -static
